EXEC SUPERUSER.reset_data('loan_repayments');
EXEC SUPERUSER.reset_data('loan_disbursements');
EXEC SUPERUSER.reset_data('loan_applications');
EXEC SUPERUSER.reset_data('loan_officers');
EXEC SUPERUSER.reset_data('loan_applicants');

EXEC SUPERUSER.reset_seq('REPAYMENT_ID_SEQ', 500001);
EXEC SUPERUSER.reset_seq('DISBURSEMENT_ID_SEQ', 400001);
EXEC SUPERUSER.reset_seq('APPLICATION_ID_SEQ', 300001);
EXEC SUPERUSER.reset_seq('OFFICER_ID_SEQ', 200001);
EXEC SUPERUSER.reset_seq('APPLICANT_ID_SEQ', 100001);

EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'johndoe', SUPERUSER.STANDARD_HASH_OUTPUT('password7871'), 'John', 'Doe', 'johndoe@email.com', '1234567890', '123 Main St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'janedoe', SUPERUSER.STANDARD_HASH_OUTPUT('password1234'), 'Jane', 'Doe', 'janedoe@email.com', '2345678901', '456 First St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'bobsmith', SUPERUSER.STANDARD_HASH_OUTPUT('passwordabcd'), 'Bob', 'Smith', 'bobsmith@email.com', '3456789012', '789 Second St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'sallyjones', SUPERUSER.STANDARD_HASH_OUTPUT('password5578'), 'Sally', 'Jones', 'sallyjones@email.com', '4567890123', '012 Third St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'tomwilliams', SUPERUSER.STANDARD_HASH_OUTPUT('passwordxyz'), 'Tom', 'Williams', 'tomwilliams@email.com', '5678901234', '345 Fourth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'carolbrown', SUPERUSER.STANDARD_HASH_OUTPUT('password1734'), 'Carol', 'Brown', 'carolbrown@email.com', '6789012345', '678 Fifth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'franklinrodriguez', SUPERUSER.STANDARD_HASH_OUTPUT('passwordaocd'), 'Franklin', 'Rodriguez', 'franklinrodriguez@email.com', '7890123456', '901 Sixth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'hannahlee', SUPERUSER.STANDARD_HASH_OUTPUT('password6678'), 'Hannah', 'Lee', 'hannahlee@email.com', '8901234567', '234 Seventh St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'peterkim', SUPERUSER.STANDARD_HASH_OUTPUT('passwordxdz'), 'Peter', 'Kim', 'peterkim@email.com', '9012345678', '567 Eighth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'marynguyen', SUPERUSER.STANDARD_HASH_OUTPUT('password1534'), 'Mary', 'Nguyen', 'marynguyen@email.com', '0123456789', '890 Ninth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'jimmyli', SUPERUSER.STANDARD_HASH_OUTPUT('passwordapcd'), 'Jimmy', 'Li', 'jimmyli@email.com', '1234567891', '123 Tenth St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'jameydoe', SUPERUSER.STANDARD_HASH_OUTPUT('password1034'), 'Jamey', 'Doe', 'jameydoe@email.com', '0987654321', '456 Elm St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'samjones', SUPERUSER.STANDARD_HASH_OUTPUT('password4567'), 'Sam', 'Jones', 'samjones@email.com', '1112223333', '789 Oak Ave');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'alexsmith', SUPERUSER.STANDARD_HASH_OUTPUT('password7890'), 'Alex', 'Smith', 'alexsmith@email.com', '4445556666', '321 Pine Rd');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'amandawoods', SUPERUSER.STANDARD_HASH_OUTPUT('password5778'), 'Amanda', 'Woods', 'amandawoods@email.com', '7778889999', '654 Cedar Ln');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'davidlee', SUPERUSER.STANDARD_HASH_OUTPUT('password2968'), 'David', 'Lee', 'davidlee@email.com', '3334445555', '987 Maple St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'nataliejackson', SUPERUSER.STANDARD_HASH_OUTPUT('password1357'), 'Natalie', 'Jackson', 'nataliejackson@email.com', '8889990000', '654 Pine St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'ryanmiller', SUPERUSER.STANDARD_HASH_OUTPUT('password3690'), 'Ryan', 'Miller', 'ryanmiller@email.com', '4443332222', '789 Cedar Ave');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'jacobturner', SUPERUSER.STANDARD_HASH_OUTPUT('password8024'), 'Jacob', 'Turner', 'jacobturner@email.com', '5554443333', '987 Oak Rd');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'emilyroberts', SUPERUSER.STANDARD_HASH_OUTPUT('password2468'), 'Emily', 'Roberts', 'emilyroberts@email.com', '2223334444', '321 Cedar St');
EXEC SUPERUSER.admin_insert_pack.insert_loan_applicants_proc(SUPERUSER.APPLICANT_ID_SEQ.NEXTVAL,'ericbrown', SUPERUSER.STANDARD_HASH_OUTPUT('password1857'), 'Eric', 'Brown', 'ericbrown@email.com', '7776665555', '654 Elm Ave');
commit;


EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'emmawilson', SUPERUSER.STANDARD_HASH_OUTPUT('password231'), 'Emma', 'Wilson', 'emma.wilson@email.com', '5551234567');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'johnsmith', SUPERUSER.STANDARD_HASH_OUTPUT('password4561'), 'John', 'Smith', 'john.smith@email.com', '5552345678');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'jessicamiller', SUPERUSER.STANDARD_HASH_OUTPUT('password789'), 'Jessica', 'Miller', 'jessica.miller@email.com', '5553456789');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'ryanlee', SUPERUSER.STANDARD_HASH_OUTPUT('password012'), 'Ryan', 'Lee', 'ryan.lee@email.com', '5554567890');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'katebrown', SUPERUSER.STANDARD_HASH_OUTPUT('password345'), 'Kate', 'Brown', 'kate.brown@email.com', '5555678901');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'williamjones', SUPERUSER.STANDARD_HASH_OUTPUT('password678'), 'William', 'Jones', 'william.jones@email.com', '5556789012');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'sarahwang', SUPERUSER.STANDARD_HASH_OUTPUT('password901'), 'Sarah', 'Wang', 'sarah.wang@email.com', '5557890123');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'davidtaylor', SUPERUSER.STANDARD_HASH_OUTPUT('password234'), 'David', 'Taylor', 'david.taylor@email.com', '5558901234');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'amynguyen', SUPERUSER.STANDARD_HASH_OUTPUT('password567'), 'Amy', 'Nguyen', 'amy.nguyen@email.com', '5559012345');
EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'markdavis', SUPERUSER.STANDARD_HASH_OUTPUT('password890'), 'Mark', 'Davis', 'mark.davis@email.com', '5550123456');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'sophialewis', SUPERUSER.STANDARD_HASH_OUTPUT('password1239'), 'Sophia', 'Lewis', 'sophia.lewis@email.com', '5551234567');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'danielkim', SUPERUSER.STANDARD_HASH_OUTPUT('password4562'), 'Daniel', 'Kim', 'daniel.kim@email.com', '5552345678');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'tomhanks', SUPERUSER.STANDARD_HASH_OUTPUT('password321'), 'Tom', 'Hanks', 'tomhanks@email.com', '5559876543');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'jenniferlopez', SUPERUSER.STANDARD_HASH_OUTPUT('password1023'), 'Jennifer', 'Lopez', 'jennifer.lopez@email.com', '5551112222');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'brucelee', SUPERUSER.STANDARD_HASH_OUTPUT('password8456'), 'Bruce', 'Lee', 'bruce.lee@email.com', '5553334444');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'angelinajolie', SUPERUSER.STANDARD_HASH_OUTPUT('password7800'), 'Angelina', 'Jolie', 'angelina.jolie@email.com', '5555551212');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'georgeclooney', SUPERUSER.STANDARD_HASH_OUTPUT('password999'), 'George', 'Clooney', 'george.clooney@email.com', '5557778888');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'merylstreep', SUPERUSER.STANDARD_HASH_OUTPUT('password777'), 'Meryl', 'Streep', 'meryl.streep@email.com', '5552223333');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'jimcarrey', SUPERUSER.STANDARD_HASH_OUTPUT('password555'), 'Jim', 'Carrey', 'jim.carrey@email.com', '5554445555');
-- EXEC SUPERUSER.admin_insert_pack.insert_loan_officers_proc(SUPERUSER.OFFICER_ID_SEQ.NEXTVAL,'scarlettjohansson', SUPERUSER.STANDARD_HASH_OUTPUT('password333'), 'Scarlett', 'Johansson', 'scarlett.johansson@email.com', '5556667777');
commit;

EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100001, 200001,50000,'approved',50000,12,6);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100002, 200002,75000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100003, 200003,25000,'approved',25000,6,7);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100004, 200004,80000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100005, 200005,60000,'approved',60000,9,5);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100006, 200006,45000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100007, 200007,20000,'approved',20000,3,8);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100008, 200008,35000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100009, 200009,90000,'approved',90000,12,4);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100010, 200010,55000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100011, 200001,75000,'approved',70000,2,6.5);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100012, 200002,60000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100013, 200003,80000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100014, 200004,90000,'approved',85000,5,7);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100015, 200005,50000,'approved',45000,2,5.5);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100016, 200006,75000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100017, 200007,40000,'approved',35000,6,4.5);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100018, 200008,70000,'approved',65000,2,6);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100019, 200009,95000,'rejected',0,0,0);
EXEC SUPERUSER.admin_insert_pack.insert_loan_applications_proc(SUPERUSER.APPLICATION_ID_SEQ.NEXTVAL,100020, 200010,85000,'approved',80000,3,7.5);
commit;

EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300001, TO_DATE('2022-04-01', 'YYYY-MM-DD'),10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300001, TO_DATE('2022-05-02', 'YYYY-MM-DD'),10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300003, TO_DATE('2022-01-02', 'YYYY-MM-DD'),5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300003, TO_DATE('2022-03-03', 'YYYY-MM-DD'),10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300005, TO_DATE('2022-05-03', 'YYYY-MM-DD'),10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300005, TO_DATE('2022-07-04', 'YYYY-MM-DD'),20000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300007, TO_DATE('2022-06-04', 'YYYY-MM-DD'),5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300007, TO_DATE('2022-08-05', 'YYYY-MM-DD'),5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300009, TO_DATE('2022-03-05', 'YYYY-MM-DD'),20000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300011, TO_DATE('2022-02-06', 'YYYY-MM-DD'),25000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300014, TO_DATE('2022-09-07', 'YYYY-MM-DD'),35000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300014, TO_DATE('2022-10-08', 'YYYY-MM-DD'),5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300015, TO_DATE('2022-11-08', 'YYYY-MM-DD'),15000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300017, TO_DATE('2022-12-09', 'YYYY-MM-DD'),15000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300018, TO_DATE('2022-11-09', 'YYYY-MM-DD'),15000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300020, TO_DATE('2022-11-10', 'YYYY-MM-DD'),20000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_disbursements_proc(SUPERUSER.DISBURSEMENT_ID_SEQ.NEXTVAL,300020, TO_DATE('2022-04-11', 'YYYY-MM-DD'),20000);
commit;

EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300001, TO_DATE('2022-05-01', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300001, TO_DATE('2022-06-02', 'YYYY-MM-DD'), 5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300003, TO_DATE('2022-03-03', 'YYYY-MM-DD'), 5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300003, TO_DATE('2022-05-04', 'YYYY-MM-DD'), 5000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300005, TO_DATE('2022-06-05', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300005, TO_DATE('2022-08-06', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300007, TO_DATE('2022-10-07', 'YYYY-MM-DD'), 4000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300007, TO_DATE('2022-09-08', 'YYYY-MM-DD'), 4000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300009, TO_DATE('2022-05-09', 'YYYY-MM-DD'), 15000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300011, TO_DATE('2022-04-10', 'YYYY-MM-DD'), 20000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300014, TO_DATE('2022-12-10', 'YYYY-MM-DD'), 4000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300014, TO_DATE('2022-11-11', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300015, TO_DATE('2022-12-30', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300017, TO_DATE('2022-12-12', 'YYYY-MM-DD'), 10000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300018, TO_DATE('2022-12-13', 'YYYY-MM-DD'), 11000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300020, TO_DATE('2022-12-14', 'YYYY-MM-DD'), 15000);
EXEC SUPERUSER.admin_insert_pack.insert_loan_repayments_proc(SUPERUSER.REPAYMENT_ID_SEQ.NEXTVAL, 300020, TO_DATE('2022-06-15', 'YYYY-MM-DD'), 10000);
commit;

